"""Add unique constraint to hero_id and power_id

Revision ID: c16f57d7d0a3
Revises: ae2ada437023
Create Date: 2025-06-18 01:17:52.095627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16f57d7d0a3'
down_revision = 'ae2ada437023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_hero_power', ['hero_id', 'power_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.drop_constraint('unique_hero_power', type_='unique')

    # ### end Alembic commands ###
